--PONER TU NOMBRE Y APELLIDOS POR PANTALLA
SET SERVEROUTPUT ON
DECLARE
    NAME VARCHAR2(100);
    LASTNAME VARCHAR2(100);   
BEGIN
    NAME:='JHON';
    LASTNAME:='CONNORS';
    DBMS_OUTPUT.PUT_LINE(NAME);
    DBMS_OUTPUT.PUT_LINE(LASTNAME);
    DBMS_OUTPUT.PUT_LINE(NAME||' '|| LASTNAME);
END;